### ISSUE TITLE
Voting Bug

### ISSUE THREAD

**Issue by Birdtalon** [Team-TS/birdbot#22]
When you vote to stop/skip a track the number of required votes increases.

**Comment by Scottx125** [comment]
Should be fixed.
How it works now: If stop and skip works the same way, it stops the current song and the autoplay will move to the next one if another is en-queued. If a user sends the command who has the admin role, the vote will pass and clear the voting list. Otherwise the votelist will check if the person who said the command is in the votelist, if not they be added. Then a check is done to see if the number of people in the list is enough for the vote to pass, if it is a check is done to ensure the people in the list are in the channel. If they are not they are removed from the list. Then a second check is done and if it passes the song is stopped and the list is cleared. Otherwise it will report the number of votes still needed and will return.
